// Website/svelte/my-svelte-project/src/Form.svelte
<script>
  let name;
  let age;
  //   let swim = false;
  //   let ball = false;
  //   let bat = false;
  let color;
  let skills = [];

  const handleSubmit = (e) => {
    // e.preventDefault();
    console.log(name, age, skills, color);
  };
</script>

<div>
  <form on:submit|preventDefault={handleSubmit}>
    <input placeholder="name" type="text" bind:value={name} />
    <input placeholder="age" type="number" bind:value={age} />

    <!-- <input type="checkbox" bind:checked={swim} />Swim
    <input type="checkbox" bind:checked={ball} />Ball
    <input type="checkbox" bind:checked={bat} />Bat -->

    <input type="checkbox" bind:group={skills} value="swim" />Swim <br />
    <input type="checkbox" bind:group={skills} value="ball" />Ball <br />
    <input type="checkbox" bind:group={skills} value="bat" />Bat
    <select bind:value={color}>
      <option value="blacck">black</option>
      <option value="red">red</option>
    </select>
    <button>Add</button>
  </form>
</div>

// Website/React/tutorial2/src/Components/Form/Form.jsx
import React, { useState } from "react";

const Form = () => {
  const [name, setName] = useState("");
  const [lname, setLname] = useState("");
  const [people, setPeople] = useState([]);
  const handleSubmit = (e) => {
    e.preventDefault();
    const data = { name, lname };
    if (name && lname) {
      setPeople((prev) => {
        return [...prev, data];
      });
    }
    console.log(people);
  };

  return (
    <div>
      <form onSubmit={handleSubmit}>
        <label htmlFor="">Name</label>
        <input
          type="text"
          value={name}
          onChange={(e) => setName(e.target.value)}
        />
        <label htmlFor="">Lastname</label>
        <input
          type="text"
          value={lname}
          onChange={(e) => setLname(e.target.value)}
        />
        <button type="submit">Submit</button>
      </form>
    </div>
  );
};

export default Form;
